### ISSUE TITLE
Link to metacpan.org for each module

### ISSUE THREAD

**Issue by hakonhagland** [charsbar/CPAN-Groonga#2]
Would it be possible to get a link to the module documentation on metacpan.org for each module in the results? That would be really handy, so I don't have to open metacpan.org in a new browser tab, and then retype the module name from the result list :)

**Comment by charsbar** [comment]
Thanks for your request. I've just implemented it and deployed.

**Comment by hakonhagland** [comment]
Thanks!! This is great, but I actually meant the documentation page. For example, searching for `PowerShell` gives me as first result `Win32-PowerShell-IPC`, and two new links to metacpan.org (as you just added), one for the release, and one for the source:

- https://metacpan.org/release/NERDVANA/Win32-PowerShell-IPC-0.02
- https://metacpan.org/source/NERDVANA/Win32-PowerShell-IPC-0.02/lib/Win32/PowerShell/IPC.pm

this great, but I ususally go to the documentation page first:

- https://metacpan.org/pod/release/NERDVANA/Win32-PowerShell-IPC-0.02/lib/Win32/PowerShell/IPC.pm

I know it easy to get to this page from the release page, but .. it would be even better (in my opinion at least) if there was a link directly to the documentation also

**Comment by charsbar** [comment]
Hm. Interesting, but that probably doesn't work for all, because not every module has a pod (or rather, not every file in that sense), and what's found is not always in the pod.

Maybe I can add an option to search for a phase only in p5/p6 pods, and then it's quite natural to link to each pod page. I can't promise to add the feature really soonish, but I'll raise another issue for this for the moment. Thanks for your idea.
